# Generated by Django 4.2.11 on 2024-05-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='Other Inquiry', max_length=200),
        ),
    ]
